# Generated by Django 3.0.6 on 2020-05-30 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drugMusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 30, 6, 6, 41, 671296, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
