# Generated by Django 3.0.6 on 2020-05-30 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugMusicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
